//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemandApp
{


    public partial class Registration
    {

        /// <summary>
        /// lblwelcome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblwelcome;

       // /// <summary>
       // /// Menu1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Menu Menu1;

       // /// <summary>
       // /// MultiView1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.MultiView MultiView1;

       // /// <summary>
       // /// tabNew control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.View tabNew;

       // /// <summary>
       // /// Label11 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label11;

       // /// <summary>
       // /// tabNew_txtdemnaddate control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.TextBox tabNew_txtdemnaddate;

       // /// <summary>
       // /// tabNew_txtdemnaddate_CalendarExtender control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.CalendarExtender tabNew_txtdemnaddate_CalendarExtender;

       // /// <summary>
       // /// Label2 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label2;

       // /// <summary>
       // /// Label3 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label3;

       // /// <summary>
       // /// tabNew_Route_Customer_Name control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Combobox tabNew_Route_Customer_Name;

       // /// <summary>
       // /// Label17 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label17;

       // /// <summary>
       // /// Label18 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label18;

       // /// <summary>
       // /// Label16 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label16;

       // /// <summary>
       // /// lblqty control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblqty;

       // /// <summary>
       // /// Button1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // //protected global::System.Web.UI.WebControls.Button Button1;

       // /// <summary>
       // /// lbledit control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lbledit;

       // /// <summary>
       // /// ImageButton8 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton ImageButton8;

       // /// <summary>
       // /// GridView1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.GridView GridView1;

       // /// <summary>
       // /// CMDSave control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       //// protected global::System.Web.UI.WebControls.ImageButton CMDSave;

       // /// <summary>
       // /// TABVERIFY control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.View TABVERIFY;

       // /// <summary>
       // /// TABVERIFY_RDB_ROUTE_TYPE control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.RadioButtonList TABVERIFY_RDB_ROUTE_TYPE;

       // /// <summary>
       // /// Label7 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label7;

       // /// <summary>
       // /// Label10 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label10;

       // /// <summary>
       // /// TABVERIFY_CMBCustomer_NAME control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.combobox TABVERIFY_CMBCustomer_NAME;

       // /// <summary>
       // /// TABVERIFY_CMD_VIEW control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton TABVERIFY_CMD_VIEW;

       // /// <summary>
       // /// TABVERIFY_CMD_Print control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton TABVERIFY_CMD_Print;

       // /// <summary>
       // /// TABVERIFY_CMD_exportExcel control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton TABVERIFY_CMD_exportExcel;

       // /// <summary>
       // /// Label8 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label8;

       // /// <summary>
       // /// GridView3 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.GridView GridView3;

       // /// <summary>
       // /// Label19 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label19;

       // /// <summary>
       // /// RadioButtonList1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.RadioButtonList RadioButtonList1;

       // /// <summary>
       // /// TABVERIFY_CMBROUTE control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.combobox TABVERIFY_CMBROUTE;

       // /// <summary>
       // /// cmdsubmit control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton cmdsubmit;

       // /// <summary>
       // /// Label9 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label9;

       // /// <summary>
       // /// tabView control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.View tabView;

       // /// <summary>
       // /// tabreport_rdbtype control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.RadioButtonList tabreport_rdbtype;

       // /// <summary>
       // /// Label12 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label12;

       // /// <summary>
       // /// tabreport_txtdemanddate control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.TextBox tabreport_txtdemanddate;

       // /// <summary>
       // /// tabreport_txtdemanddate_CalendarExtender control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.CalendarExtender tabreport_txtdemanddate_CalendarExtender;

       // /// <summary>
       // /// Label14 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label14;

       // /// <summary>
       // /// tabreport_cmbroutename control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.combobox tabreport_cmbroutename;

       // /// <summary>
       // /// ImageButton7 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton ImageButton7;

       // /// <summary>
       // /// Label15 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label Label15;

       // /// <summary>
       // /// tabreport_cmbcustomer control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.combobox tabreport_cmbcustomer;

       // /// <summary>
       // /// ImageButton5 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton ImageButton5;

       // /// <summary>
       // /// ImageButton6 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.ImageButton ImageButton6;

       // /// <summary>
       // /// GridView2 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.GridView GridView2;

       // /// <summary>
       // /// lblleaf_id control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblleaf_id;

       // /// <summary>
       // /// lblrecid control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblrecid;

       // /// <summary>
       // /// lblpaycode control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblpaycode;

       // /// <summary>
       // /// lblip control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblip;

       // /// <summary>
       // /// lblsubcompanyid control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblsubcompanyid;

       // /// <summary>
       // /// lblcompanyid control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblcompanyid;

       // /// <summary>
       // /// lblusertype control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lblusertype;

       // /// <summary>
       // /// T_LOCATION control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label T_LOCATION;

       // /// <summary>
       // /// lbldepot control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.Label lbldepot;

       // /// <summary>
       // /// SqlDataSource1 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource1;

       // /// <summary>
       // /// SqlDataSource2 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource2;

       // /// <summary>
       // /// SqlDataSource3 control.
       // /// </summary>
       // /// <remarks>
       // /// Auto-generated field.
       // /// To modify move field declaration from designer file to code-behind file.
       // /// </remarks>
       // protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSource3;
    }
}
